title: Problem Set DDP2
description: Kumpulan latihan soal pemrograman dalam bahasa Java
theme: just-the-docs

url: https://afiqilyasakmal.github.io/ddp2

aux_links:
  SCELE DDP2: https://scele.cs.ui.ac.id/course/view.php?id=4020
